import datetime
from typing import Optional, Union

from pydantic import BaseModel

from core.db.enums import ClientStatusChoices, PeerStatusChoices
from core.db.model_serializer import BasePeer, User, WireguardPeer, XrayPeer

class Client(BaseModel):
    """
    General class for operating with single client.

    Example:
    >>> client = ClientFactory(tg_id=<telegram_id>).get_client() # -> Client
    >>> client.set_status(ClientStatusChoices.STATUS_ACTIVE)
    ... True
    """
    userdata: User

    def get_all_peers(self) -> list[BasePeer]: ...
    def add_wireguard_peer(self,
                           shared_ips: str,
                           public_key: Optional[str] = None,
                           private_key: Optional[str] = None,
                           preshared_key: Optional[str] = None,
                           peer_name: Optional[str] = None,
                           is_amnezia: bool = False
                           ) -> WireguardPeer: ...
    def add_xray_peer(self) -> XrayPeer: ...
    def delete_peers_by_id(self) -> bool: ...
    def delete_peer_by_ip(self, ip_address: str) -> bool: ...
    def get_wireguard_peers(self) -> list[WireguardPeer]: ...
    def set_status(self, status: ClientStatusChoices) -> bool: ...
    def set_expire_time(self, expire_date: datetime.datetime) -> bool: ...
    def change_peer_name(self, peer_id: int, peer_name: str) -> bool: ...
    def set_peer_status(self, peer_id: int, peer_status: PeerStatusChoices) -> None: ...
    def set_peer_timer(self, peer_id: int, time: datetime.datetime) -> None: ...
    def get_connected_peers(self) -> list[WireguardPeer]: ...

class ClientFactory(BaseModel):
    """Class for creating `Client`s."""
    user_id: Optional[int]
    def get_or_create_client(self, name: str, **kwargs) -> Client: ...

    def get_client(self) -> Optional[Client]: ...

    @staticmethod
    def select_clients() -> list[Client]: ...

    @staticmethod
    def get_peer(ip_address: str) -> Optional[WireguardPeer]: ...

    def delete_client(self) -> bool: ...

    @staticmethod
    def delete_client_by_id(user_id: Union[int, str]) -> bool: ...

    @staticmethod
    def count_clients() -> int: ...

    @staticmethod
    def get_latest_peer_id() -> int: ...

    @staticmethod
    def get_used_ip_addresses() -> list[str]: ...

    @staticmethod
    def delete_peer(peer: BasePeer) -> bool: ...
